### ISSUE TITLE
Menu-editor throws errors..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#1405]
Lately, I'm seeing this error message pop up: 

```

<br />
<b>Fatal error</b>:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Unable to parse at line 1 (near &quot;Menu editor&quot;).' in [snip]vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php:281
Stack trace:
#0 [snip]vendor/symfony/translation/Symfony/Component/Translation/Loader/YamlFileLoader.php(51): Symfony\Component\Yaml\Parser-&gt;parse('Menu editor?===...')
#1 [snip]vendor/symfony/translation/Symfony/Component/Translation/Translator.php(275): Symfony\Component\Translation\Loader\YamlFileLoader-&gt;load('/Users/bob/Site...', NULL, 'messages')
#2 [snip]vendor/symfony/translation/Symfony/Component/Translation/Translator.php(257): Symfony\Component\Translation\Translator-&gt;doLoadCatalogue(NULL)
#3 [snip]vendor/symfony/translation/Symfony/Component/Translation/Translator.php(202): Symfony\Component\Translation\Translator-&gt;loadCatalogue(NULL)
#4 [snip]app/classes/lib.php(1233): Symfony\Component\Translation\Translato in <b>[snip]vendor/symfony/translation/Symfony/Component/Translation/Loader/YamlFileLoader.php</b> on line <b>53</b><br />
```

What happens is that in this line in [extension.php, line 92](https://github.com/bolt/bolt/blob/master/app/extensions/MenuEditor/extension.php#L92)

```
                    $this->app['translator']->addResource('yml', $fileInfo->getRealPath(), $this->app['locale']);
```

It tries to add `MenuEditor/translations/readme_de.md` as a translation resource, which is obviously not going to work, because it's a Markdown file, and not something the translator can handle. 

@bacbos Do you know how this can happen?

**Comment by CarsonF** [comment]
Here was the real problem https://github.com/silexphp/Silex/commit/57d74eb0ab09ba19b6c8d356da87e2c22e7949fa

I would opt to remove the patch now
