### ISSUE TITLE
Editing a page after removing "templatefields" gives Fatal error.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5137]
Details
-------

 - Relevant Bolt Version: [ master ]

Reproduction
------------

 1. Make sure your `theme.yml` has some templatefields. (like the base-2016 theme)
 2. Create a new page, select the `extrafields.twig` template.
 3. Save the page, go to Dashboard
 4. Edit the `theme.yml`, remove the `templatefields` section.
 5. Edit the newly created page. Refresh page, if needed. 
 6. Fatal error should appear:

```
PHP Fatal error: Bolt core
Error: Uncaught Error: Call to a member function getContenttype() on array in /src/Storage/ContentRequest/Edit.php:128

Stack trace:

#0 /src/Controller/Backend/Records.php(89): Bolt\Storage\ContentRequest\Edit->action(Object(Bolt\Storage\Entity\Content), Array, false)

#1 [internal function]: Bolt\Controller\Backend\Records->edit(Object(Symfony\Component\HttpFoundation\Request), 'pages', '25')

#2 /vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array)

#3 /vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)

#4 /vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)

#5 /vendor/silex/silex/src/Silex/Application.php(563): Silex\App

File: /src/Storage/ContentRequest/Edit.php
Line: 128
```

![screenshot 2016-04-06 20 13 25](https://cloud.githubusercontent.com/assets/1833361/14327774/0e998628-fc34-11e5-838e-7c91e6756fa7.png)

**Comment by GawainLynch** [comment]
Fixed in #5139
